### ISSUE TITLE
messages.yml sign missing

### ISSUE THREAD

**Issue by HelllReaper** [Lyzard-Network/FoliaTpa#1]
I found some missing ">" in the color parameters.
Btw i rewrote it in spanish, ty for the folia plugin, great job <3

_"Hai` ricevuto una richiesta di Teletrasporto da  <#ffff33{player}</#ffff33"_

```
#Spanish code
TPA:
  USAGE: "<#ffff33>Lyzard</#ffff33> » Utiliza /tpa <jugador>"
  CANT_SELF: "<#ffff33>Lyzard</#ffff33> » No puedes mandarte una solicitud de teletransporte a ti mismo :(."
  ALREADY_SENT: "<#ffff33>Lyzard</#ffff33> » Espera antes de volver a mandar una solicitud a este jugador."
  SUCCESS: "<#ffff33>Lyzard</#ffff33> » Has enviado una solicitud de teletransporte al jugador --> <#ffff33>{player}</#ffff33>."
  TARGET_RECEIVED: "Has recibido una solicitud de teletransporte de --> <#ffff33>{player}</#ffff33>"
  TARGET_ACCEPT: "<#00cc00>[PRESIONA PARA ACEPTAR]</#00cc00> o usa /tpaccept <jugador>."
  TARGET_ACCEPT_HOVER: "<#00cc00>[ACEPTAR]</#00cc00>"

ERRORS:
  PLAYER-NOT-ONLINE: "Lyzard » El jugador no se encuentra conectado en este momento :(."

TPA_HERE:
  USAGE: "<#ffff33>Lyzard</#ffff33> » Utiliza /tpahere <jugador>"
  TARGET_RECEIVED: "Has recibido una peticion de teletransporte hacia el jugador --> <#ffff33>{player}</#ffff33>"
  TARGET_ACCEPT: "<#00cc00>[PRESIONA PARA ACEPTAR]</#00cc00> o usa /tpaccept <jugador>."
  TARGET_ACCEPT_HOVER: "<#00cc00>[ACEPTAR]</#00cc00>"

TPA_ACCEPT:
  USAGE: "<#ffff33>Lyzard</#ffff33> » Utiliza /tpaccept <jugador>"
  NO_REQUEST: "<#ffff33>Lyzard</#ffff33> » Este jugador no te ha enviado una solicitud de teletransporte."
  ACCEPTED: "<#ffff33>Lyzard</#ffff33> » Solicitud de teletransporte <#00cc00>aceptada</#00cc00>"


```
